### ISSUE TITLE
Event script is called even if associated thing is not built

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsModBuilder#28]
```
Call script D:\Projects\TheSuperHackers\GeneralsGamePatch\Patch104pZH\Scripts\Python\OnBuildItemWithBlender3-4-1 ...
Script OnBuildItemWithBlender3-4-1.py called ...
Call script D:\Projects\TheSuperHackers\GeneralsGamePatch\Patch104pZH\Scripts\Python\OnBuildItemWithBlender3-4-1 ...
Script OnBuildItemWithBlender3-4-1.py called ...
ERROR CALLSTACK
Traceback (most recent call last):
  File "gui\gui.py", line 410, in _DoWork
  File "gui\gui.py", line 305, in <lambda>
  File "buildfunctions.py", line 115, in RunWithConfig
  File "build\engine.py", line 290, in Run
  File "build\engine.py", line 582, in __Build
  File "build\engine.py", line 631, in __BuildWithData
  File "build\engine.py", line 361, in __SendBundleEvents
  File "build\engine.py", line 335, in __CallScript
  File "D:\Projects\TheSuperHackers\GeneralsGamePatch\Patch104pZH\Scripts\Python\OnBuildItemWithBlender3-4-1.py", line 100, in OnEvent
    raise Exception("Unable to reference '{RAW_BUILD_THING}' in user script")
Exception: Unable to reference '{RAW_BUILD_THING}' in user script
```

bug?

**Comment by xezon** [comment]
Workaround in #1883

**Comment by xezon** [comment]
As designed.
