### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsModBuilder#29]
Posted here:
https://www.gamereplays.org/community/index.php?s=&showtopic=1056128&view=findpost&p=10546121

```
Run Build Job ...
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\ModBundleItems.json in 0.027 s
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\ModBundleAudioItems.json in 0.016 s
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\ModBundleLanguageItems.json in 0.011 s
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\ModBundleCorePacks.json in 0.011 s
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\ModBundleFullPacks.json in 0.014 s
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\ModChangeLog.json in 0.011 s
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\ModFolders.json in 0.011 s
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\Scripts\Windows\WindowsRunner.json in 0.014 s
Read json G:\Downloads\GeneralsGamePatch-main\Patch104pZH\Scripts\Windows\WindowsTools.json in 0.014 s
Get registry key SOFTWARE\Electronic Arts\EA Games\Command and Conquer Generals Zero Hour : InstallPath as 'G:\Games\C&C Generals - Deluxe Edition\Command & Conquer Generals Zero Hour'
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesEdited\Art\Textures\NoMip\*.tga' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesEdited\Art\Models\Animation\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesEdited\Art\Models\Hierarchy\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesEdited\Art\Models\HierarchyAnimationMesh\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesEdited\Art\Models\HierarchyMesh\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesEdited\Art\Models\Mesh\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\Textures\*.dds' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\Textures\NoMip\*.psd' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\Textures\NoMip\*.tga' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\W3D\*.W3D' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\Models\Animation\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\Models\Hierarchy\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\Models\HierarchyAnimationMesh\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\Models\HierarchyMesh\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOptional\Art\Models\Mesh\*.blend' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOriginalCCG\Art\Textures\*.tga' currently matches nothing
Note: Wildcard 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\GameFilesOriginalCCG\Art\Textures\GenerateMip\*.tga' currently matches nothing
Bundles.VerifyValues completed in 0.129 s
Downloading 1004 kb from 'https://github.com/TheSuperHackers/GeneralsTools/raw/main/Tools/crunch/v1.04/crunch_x64.exe' ...
Hashed (1) G:\Downloads\GeneralsGamePatch-main\Patch104pZH\Scripts\Windows\.tools\crunch_x64.exe as 8ae949bfc3e3e4a1717dca8845ce8ed480638de68cbf1d7cbe912e99e35ce06f in 0.237 s
Tool 'crunch 1.04' file 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\Scripts\Windows\.tools\crunch_x64.exe' is installed
Downloading 926 kb from 'https://github.com/TheSuperHackers/GeneralsTools/raw/main/Tools/gametextcompiler/v1.1/gametextcompiler.exe' ...
Hashed (2) G:\Downloads\GeneralsGamePatch-main\Patch104pZH\Scripts\Windows\.tools\gametextcompiler.exe as 9c4c50f9c4829caff9b913bdd1a398a3a323ae9a1599723ff71ac675f6087467 in 1.799 s
Tool 'gametextcompiler 1.1' file 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\Scripts\Windows\.tools\gametextcompiler.exe' is installed
Downloading 67 kb from 'https://github.com/TheSuperHackers/GeneralsTools/raw/main/Tools/generalsbigcreator/v1.3/generalsbigcreator.exe' ...
Hashed (3) G:\Downloads\GeneralsGamePatch-main\Patch104pZH\Scripts\Windows\.tools\generalsbigcreator.exe as 213ce479a033db949f19012a7e4270cf6c83a79282c1b1941f625b825c1451ed in 0.077 s
Tool 'generalsbigcreator 1.3' file 'G:\Downloads\GeneralsGamePatch-main\Patch104pZH\Scripts\Windows\.tools\generalsbigcreator.exe' is installed
ERROR CALLSTACK
Traceback (most recent call last):
File "urllib\request.py", line 1348, in do_open
File "http\client.py", line 1282, in request
File "http\client.py", line 1328, in _send_request
File "http\client.py", line 1277, in endheaders
File "http\client.py", line 1037, in _send_output
File "http\client.py", line 975, in send
File "http\client.py", line 1454, in connect
File "ssl.py", line 512, in wrap_socket
File "ssl.py", line 1070, in _create
File "ssl.py", line 1341, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "main.py", line 133, in Main
File "main.py", line 117, in RunWithConfigWrapper
File "buildfunctions.py", line 93, in RunWithConfig
File "data\tools.py", line 408, in InstallTools
File "data\tools.py", line 284, in Install
File "data\tools.py", line 160, in Install
File "urllib\request.py", line 216, in urlopen
File "urllib\request.py", line 519, in open
File "urllib\request.py", line 536, in _open
File "urllib\request.py", line 496, in _call_chain
File "urllib\request.py", line 1391, in https_open
File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
Press any key to continue...
```

**Comment by xezon** [comment]
https://support.chainstack.com/hc/en-us/articles/9117198436249-Common-SSL-Issues-on-Python-and-How-to-Fix-it

**Comment by xezon** [comment]
For starters I will try with certifi package and see if that works.

https://pypi.org/project/certifi/
