### ISSUE TITLE
Blender does not download for everyone

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsModBuilder#40]
Blender does not download for everyone.

```
Install Mod Builder ...
Setup ...
Using Mod Builder version 2.1
Archive size 32209682
Archive sha256 7357871f9e173373b4d7de8385a2cd23c8a3210cd103373830cd2460bfc7acd8
Archive url https://github.com/TheSuperHackers/GeneralsModBuilder/releases/download/v2.1/generalsmodbuilder_v2.1.7z
Archive path C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\.modbuilder\v2.1\generalsmodbuilder.7zInstall path C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\.modbuilder\v2.1
Executable path C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\.modbuilder\v2.1\generalsmodbuilder\generalsmodbuilder.exe
Configuration files:
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleCoreAudioItems.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleCoreItems.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleCoreLanguageItems.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleOptionalAudioItems.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleOptionalItems.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleOptionalLanguageItems.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleRecoveredItems.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleCorePacks.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModBundleFullPacks.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModChangeLog.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\..\..\ModFolders.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\WindowsRunner.json"
"C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.\WindowsTools.json"
Generals Mod Builder is installed
Setup ...
Generals Mod Builder v2.1 by The Super Hackers
instance(Namespace):
  build: True,
  build_pack: None,
  build_pack_list: None,
  clean: False,
  config: None,
  config_list: [
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleCoreAudioItems.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleCoreItems.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleCoreLanguageItems.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleOptionalAudioItems.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleOptionalItems.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleOptionalLanguageItems.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleRecoveredItems.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleCorePacks.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModBundleFullPacks.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModChangeLog.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\..\\..\\ModFolders.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\WindowsRunner.json',
    'C:\\Users\\username\\DOWNLO~1\\GENERA~1\\GENERA~1\\PATCH1~1\\Scripts\\Windows\\.\\WindowsTools.json',
  ],
  debug: False,
  file_hash_registry_input: None,
  file_hash_registry_name: 'FileHashRegistry',
  file_hash_registry_output: None,
  gui: False,
  install: [
    'FullEnglish',
  ],
  install_list: None,
  load_default_runner: False,
  load_default_tools: False,
  make_change_log: False,
  print_config: False,
  release: False,
  run: True,
  tools_root_dir: None,
  uninstall: True
Run Build Job ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleCoreAudioItems.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleCoreItems.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleCoreLanguageItems.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleOptionalAudioItems.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleOptionalItems.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleOptionalLanguageItems.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleRecoveredItems.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleCorePacks.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModBundleFullPacks.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModChangeLog.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\ModFolders.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\WindowsRunner.json ...
Read json C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\WindowsTools.json ...
Get registry key SOFTWARE\Electronic Arts\EA Games\Command and Conquer Generals Zero Hour : InstallPath as 'C:\Program Files (x86)\R.G. Mechanics\Command and Conquer - Generals\Command and Conquer Generals Zero Hour\'
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesEdited\Art\Textures\NoMip\*.tga' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesEdited\Art\Models\Animation\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesEdited\Art\Models\Hierarchy\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesEdited\Art\Models\HierarchyAnimationMesh\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesEdited\Art\Models\HierarchyMesh\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesEdited\Art\Models\Mesh\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Textures\*.dds' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Textures\GenerateMipHalf\*.tga' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Textures\NoMip\*.psd' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Textures\NoMip\*.tga' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\W3D\*.W3D' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Models\Animation\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Models\Hierarchy\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Models\HierarchyAnimationMesh\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Models\HierarchyMesh\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOptional\Art\Models\Mesh\*.blend' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOriginalCCG\Art\Textures\*.tga' currently matches nothing
Note: Wildcard 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\GameFilesOriginalCCG\Art\Textures\GenerateMip\*.tga' currently matches nothing
Bundles.VerifyValues completed in 0.037 s
Hashed (1) C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.tools\crunch_x64.exe as 8ae949bfc3e3e4a1717dca8845ce8ed480638de68cbf1d7cbe912e99e35ce06f in 0.001 s
Tool 'crunch 1.04' file 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.tools\crunch_x64.exe' is installed
Hashed (2) C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.tools\gametextcompiler.exe as 9c4c50f9c4829caff9b913bdd1a398a3a323ae9a1599723ff71ac675f6087467 in 0.001 s
Tool 'gametextcompiler 1.1' file 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.tools\gametextcompiler.exe' is installed
Hashed (3) C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.tools\generalsbigcreator.exe as 213ce479a033db949f19012a7e4270cf6c83a79282c1b1941f625b825c1451ed in 0.000 s
Tool 'generalsbigcreator 1.3' file 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.tools\generalsbigcreator.exe' is installed
Downloading from 'https://ftp.halifax.rwth-aachen.de/blender/release/Blender3.4/blender-3.4.1-windows-x64.zip' ...
Using cafile 'C:\Users\username\DOWNLO~1\GENERA~1\GENERA~1\PATCH1~1\Scripts\Windows\.modbuilder\v2.1\generalsmodbuilder\certifi\cacert.pem'
ERROR CALLSTACK
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1283, in request
  File "http\client.py", line 1329, in _send_request
  File "http\client.py", line 1278, in endheaders
  File "http\client.py", line 1038, in _send_output
  File "http\client.py", line 976, in send
  File "http\client.py", line 1448, in connect
  File "http\client.py", line 942, in connect
  File "socket.py", line 845, in create_connection
  File "socket.py", line 833, in create_connection
TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 141, in Main
  File "main.py", line 124, in RunWithConfigWrapper
  File "buildfunctions.py", line 94, in RunWithConfig
  File "data\tools.py", line 416, in InstallTools
  File "data\tools.py", line 289, in Install
  File "data\tools.py", line 165, in Install
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера>
Press any key to continue...
```

**Comment by xezon** [comment]
Blender download needs to be optional in a future release. When plain text to w3d is added, blender is only needed to generate intermediate blender files from w3d files.
